### ISSUE TITLE
Update EKS Guide to use ConfigGroup v2

### ISSUE THREAD

**Issue by EronWright** [pulumi/docs#11455]
[This section](https://www.pulumi.com/docs/clouds/aws/guides/eks/#deploying-existing-kubernetes-yaml-config-to-your-eks-cluster) of the EKS Guide says "This functionality is currently not available in YAML." for the YAML language. Based on the info in [this blog post](https://github.com/pulumi/pulumi-hugo/pull/4043), we can now include a YAML example in this section.

The subsequent section featuring a transformation is still not possible.

Here's a draft of the new content:

```yaml
resources:
  eks-provider:
    type: pulumi:providers:kubernetes
    properties:
      kubeconfig: ${cluster.kubeconfigJson}
  cluster:
    type: eks:Cluster
  guestbook:
    type: kubernetes:yaml/v2:ConfigGroup
    properties:
      files:
      - "yaml/*.yaml"
    options:
      provider: ${eks-provider}
outputs:
  kubeconfig: ${cluster.kubeconfig}
```
