### ISSUE TITLE
Document the `quickstart` property for templates

### ISSUE THREAD

**Issue by zbuchheit** [pulumi/docs#11460]
I have a use case for `template:quickstart:` in my program, and was unaware it existed because it doesn't seem to be documented.

Example this quickstart value is output once I create the template
```yaml
name: ${PROJECT}
description: ${DESCRIPTION}
runtime: nodejs
template:
  quickstart: |
    Please check your program once it is generated.
    This is my multiline string
    Also have fun!
  description: "A minimal Azure Native Typescript Pulumi program"
  important: true
  config:
    azure-native:location:
      description: The Azure location to use
      default: WestUS2

```
References:
https://github.com/pulumi/pulumi/blob/master/sdk/go/common/workspace/project.json

File: [themes/default/content/docs/concepts/projects/project-file.md](https://www.pulumi.com/docs/concepts/projects/project-file/)
