### ISSUE TITLE
No clear way how to get ESC secrets in a Pulumi application

### ISSUE THREAD

**Issue by kennethlynne** [pulumi/docs#11526]
File: [themes/default/content/docs/concepts/secrets.md](https://www.pulumi.com/docs/concepts/secrets/)
I am just starting out with Pulumi and ESC.

I could not figure out from the documentation how to get a secret from Pulumi ESC and make use of it in my application.

I have created the secret and imported it in my stack, and I can successfully deploy for example a EKS cluster relying on the magic behind the scenes that sets it as environment variables, but when I want to pass something to a provider it was very hard to figure out how to get the secret correctly. 

Example that I expect to work:

My environment definition:
```
values:
  aws:
    login:
      fn::open::aws-login:
        oidc:
          duration: 1h
          roleArn: arn:aws:iam::730335356113:role/PulumiSuperadmin
          sessionName: pulumi-environments-session
  secrets:
    fn::open::aws-secrets:
      region: eu-north-1
      login: ${aws.login}
      get:
        vercelAPIToken:
          secretId: production/platform/vercel_access_token
  environmentVariables:
    AWS_REGION: eu-north-1
    AWS_ACCESS_KEY_ID: ${aws.login.accessKeyId}
    AWS_SECRET_ACCESS_KEY: ${aws.login.secretAccessKey}
    AWS_SESSION_TOKEN: ${aws.login.sessionToken}
    VERCEL_ACCESS_TOKEN: ${secrets.vercelAPIToken}
```

In my application (typescript):
```
const vercelProvider = new vercel.Provider('vercel', {
  apiToken: config.requireSecret('vercelAPIToken'),
});
```

But I receive the error:
```
    error: Missing required configuration variable 'panoptiq-infrastructure:vercelAPIToken'
        please set a value using the command `pulumi config set --secret panoptiq-infrastructure:vercelAPIToken <value>`
```

I was expecting to be able to use it like I do above, and I think I have misunderstood something? I struggled to find any relevant documentation.

My current workaround feels very hacky and clumsy, but it gets the job done:
```
if (!process.env.VERCEL_ACCESS_TOKEN) {
  throw new Error('VERCEL_ACCESS_TOKEN is required');
}

const vercelProvider = new vercel.Provider('vercel', {
  apiToken: process.env.VERCEL_ACCESS_TOKEN,
});
```
