### ISSUE TITLE
Confusing esc gcp example

### ISSUE THREAD

**Issue by aureq** [pulumi/docs#11866]
File: [content/docs/esc/providers/gcp-login.md](https://www.pulumi.com/docs/esc/providers/gcp-login/)

I used the example in the page above without realizing that `values:` was missing at the top of the provided YAML content.
It took me quite some time to figure it out because the ESC UI doesn't make it obvious this is missing.

It would be great if the doc could show `values:` as shown below.

```yaml
gcp:
  login:
    fn::open::gcp-login:
      project: 123456789
      oidc:
        workloadPoolId: pulumi-esc
        providerId: pulumi-esc
        serviceAccount: pulumi-esc@foo-bar-123456.iam.gserviceaccount.com
```

```yaml
values:
  gcp:
    login:
      fn::open::gcp-login:
        project: 123456789
        oidc:
          workloadPoolId: pulumi-esc
          providerId: pulumi-esc
          serviceAccount: pulumi-esc@foo-bar-123456.iam.gserviceaccount.com
```
