### ISSUE TITLE
ESC: Move Sync from a Blog Post to Docs

### ISSUE THREAD

**Issue by jkodroff** [pulumi/docs#14287]
### Problem description

@komalali wrote a fine blog post on secrets sync, a use case where secrets are defined in ESC, and then pushed to other systems via Pulumi IaC: <https://www.pulumi.com/blog/esc-sync-with-iac/>

We talk about secrets sync as a somewhat prominent use case for ESC, but the blog post is the only mention - this needs to go in the docs.

The blog post itself does a very good job of explaining the technical problem the example solves, so it's mostly ready to go. However, it would _really_ benefit from a diagram or two (one is probably sufficient to show what is being synced to where).

We also don't really have a standard "patterns and practices", so it might go best under "Get Started", since that section has "retrieve secrets from external sources", which is clearly related to this topic.

**Comment by jkodroff** [comment]
It's not clear to me why this example imports another environment instead of putting everything in a single environment:

```yaml
imports:
  - my-project/my-imported-env@stable
values:
  sync:
    awsSecretsManager:
      value:
        myConfigKey: ${my-imported-env-foo}
        myNestedKey:
          haha: ${my-imported-env-bar}
        mySecret: ${my-imported-env-password}
      name: name-in-secrets-manager
```

Happy to serve as a reviewer if we move forward with this.
