### ISSUE TITLE
Table content is squished, even on larger screens

### ISSUE THREAD

**Issue by aureq** [pulumi/docs#15106]
(Reported by a customer)

Hi

Some parts of our documentation aren't usable, especially when a table with dense content is present (see links below). Basically, cells are so tight that single words are split across multiple lines making this unnecessarily difficult to read and understand.

![Image](https://github.com/user-attachments/assets/bcdc6c31-45b7-44fd-ac37-0401f1f2eae6)

![Image](https://github.com/user-attachments/assets/8a8b0916-5067-4ae3-93bd-56f8e2c98852)

Here are the links for the 2 screen captures above... but this is affecting most of our pages, including providers.

* https://www.pulumi.com/docs/iac/using-pulumi/extending-pulumi/schema/
* https://www.pulumi.com/docs/iac/using-pulumi/extending-pulumi/

Fiddling a bit and here is a possible change. This would allow using the entire browser viewport.

```css
.docs-list-main .docs-main-content-wrapper .docs-main-content {
	margin-left: 3%;
    /* `max-width: 80%` seems like a sweet spot for larger screens */
	max-width: fit-content;
	min-width: 0;
	margin-right: 3%;
}
```

**Comment by aureq** [comment]
It was pointed out to me there's this little top-right icon to partially expand.

![Image](https://github.com/user-attachments/assets/86125fe8-3737-4506-ad8e-80e06e1fb5ce)

`1200px` is better, but having a relative size might be even better.

```css
.docs-list-main .docs-main-content-wrapper .docs-content-width-expanded {
	max-width: 80% !important;
}
```
