### ISSUE TITLE
Add docs for `template` section in `Pulumi.yaml`

### ISSUE THREAD

**Issue by lukehoban** [pulumi/docs#2164]
This should be documented at https://www.pulumi.com/docs/intro/concepts/project/.

```yaml
name: aws-go-s3-folder
runtime: go
description: A static website hosted on AWS S3
template:
  config:
    aws:region:
      description: The AWS region to deploy into
      default: us-west-2
```
