### ISSUE TITLE
Missing virtualenv option on runtime object

### ISSUE THREAD

**Issue by Sodki** [pulumi/docs#3751]
File: [docs/intro/concepts/project.md](https://www.pulumi.com/docs/intro/concepts/project/)

Hi, when describing the structure of the `runtime` object, it's not mentioned that `options` also accepts `virtualenv`, which is used to indicate the Python virtual environment on Python projects. This is great because now we don't need to activate the virtualenv if we want to use Pulumi. 

For example:

```
name: test
runtime:
  name: python
  options:
    virtualenv: venv
```
