### ISSUE TITLE
AWS Golang Getting Started example fails

### ISSUE THREAD

**Issue by jamtur01** [pulumi/docs#5870]
### Problem description

I created a new AWS Golang project using the [Getting Started guide](https://www.pulumi.com/docs/get-started/aws/create-project/).

```
pulumi new aws-go
Manage your Pulumi stacks by logging in.
Run `pulumi login --help` for alternative login options.
Enter your access token from https://app.pulumi.com/account/tokens
    or hit <ENTER> to log in using your browser                   :
We've launched your web browser to complete the login process.

Waiting for login to complete...


  Welcome to Pulumi!

  Pulumi helps you create, deploy, and manage infrastructure on any cloud using
  your favorite language. You can get started today with Pulumi at:

      https://www.pulumi.com/docs/get-started/

  Tip of the day: Resources you create with Pulumi are given unique names (a randomly
  generated suffix) by default. To learn more about auto-naming or customizing resource
  names see https://www.pulumi.com/docs/intro/concepts/programming-model/#autonaming.


This command will walk you through creating a new Pulumi project.

Enter a value or leave blank to accept the (default), and press <ENTER>.
Press ^C at any time to quit.

project name: (pulumi-post)
project description: (A minimal AWS Go Pulumi program)
Created project 'pulumi-post'

Please enter your desired stack name.
To create a stack in an organization, use the format <org-name>/<stack-name> (e.g. `acmecorp/dev`).
stack name: (dev) jamtur01/dev
Created stack 'dev'

aws:region: The AWS region to deploy into: (us-east-1)
Saved config

Installing dependencies...

Finished installing dependencies

Your new project is ready to go! ✨

To perform an initial deployment, run 'pulumi up'
```

Upon actually running `pulumi up` I see:

```
pulumi up                                                                                                                                                                  (1m 6s 477ms)
Previewing update (dev)

View Live: https://app.pulumi.com/jamtur01/pulumi-post/dev/previews/shashasha

[resource plugin aws-4.0.0] installing
Downloading plugin: 72.23 MiB / 72.23 MiB [=========================] 100.00% 2s
     Type                 Name             Plan     Info
     pulumi:pulumi:Stack  pulumi-post-dev           1 error; 8 messages

Diagnostics:
  pulumi:pulumi:Stack (pulumi-post-dev):
    ../../../../pkg/mod/sourcegraph.com/sourcegraph/appdash@v0.0.0-20190731080439-ebfcffb1b5c0/opentracing/recorder.go:17:2: no required module provides package github.com/opentracing/basictracer-go; to add it:
    	go get github.com/opentracing/basictracer-go
    ../../../../pkg/mod/github.com/pulumi/pulumi/sdk/v3@v3.0.0/go/common/resource/plugin/context.go:21:2: no required module provides package github.com/opentracing/opentracing-go; to add it:
    	go get github.com/opentracing/opentracing-go
    ../../../../pkg/mod/github.com/uber/jaeger-client-go@v2.22.1+incompatible/span.go:23:2: no required module provides package github.com/opentracing/opentracing-go/ext; to add it:
    	go get github.com/opentracing/opentracing-go/ext
    ../../../../pkg/mod/github.com/uber/jaeger-client-go@v2.22.1+incompatible/baggage_setter.go:18:2: no required module provides package github.com/opentracing/opentracing-go/log; to add it:
    	go get github.com/opentracing/opentracing-go/log

    error: an unhandled error occurred: program exited with non-zero exit code: 1
```

Running:

```
go get github.com/opentracing/basictracer-go
```

Resolves the issue.

### Affected product version(s)

v3.1.0

**Comment by joeduffy** [comment]
Sorry for the troubles @jamtur01, but thanks so much for the workaround running `go get github.com/opentracing/basictracer-go`. We will get to the bottom of this right away!

**Comment by leezen** [comment]
@jamtur01 I just tried after clearing my mod cache and had trouble reproducing this:

```
❯ go clean --modcache

❯ pulumi up
Previewing update (dev)

View Live: https://app.pulumi.com/leezen/aws-go/dev/previews/e288c270-687f-40c3-99b2-920ba97ded07

     Type                 Name        Plan       Info
 +   pulumi:pulumi:Stack  aws-go-dev  create     44 messages
 +   └─ aws:s3:Bucket     my-bucket   create

Diagnostics:
  pulumi:pulumi:Stack (aws-go-dev):
    go: downloading github.com/pulumi/pulumi-aws/sdk/v4 v4.0.0
    go: downloading github.com/pulumi/pulumi/sdk/v3 v3.0.0
    go: downloading github.com/golang/protobuf v1.4.2
    go: downloading github.com/blang/semver v3.5.1+incompatible
    go: downloading github.com/hashicorp/go-multierror v1.0.0
    go: downloading github.com/pkg/errors v0.9.1
    go: downloading golang.org/x/net v0.0.0-20200602114024-627f9648deb9
    go: downloading google.golang.org/grpc v1.29.1
    go: downloading github.com/opentracing/opentracing-go v1.1.0
    go: downloading github.com/spf13/cobra v1.0.0
    go: downloading github.com/uber/jaeger-client-go v2.22.1+incompatible
    go: downloading golang.org/x/crypto v0.0.0-20200317142112-1b76d66859c6
    go: downloading sourcegraph.com/sourcegraph/appdash v0.0.0-20190731080439-ebfcffb1b5c0
    go: downloading github.com/golang/glog v0.0.0-20160126235308-23def4e6c14b
    go: downloading github.com/grpc-ecosystem/grpc-opentracing v0.0.0-20180507213350-8e809c8a8645
    go: downloading github.com/hashicorp/errwrap v1.0.0
    go: downloading github.com/cheggaaa/pb v1.0.18
    go: downloading github.com/djherbis/times v1.2.0
    go: downloading github.com/texttheater/golang-levenshtein v0.0.0-20191208221605-eb6844b05fc6
    go: downloading github.com/tweekmonster/luser v0.0.0-20161003172636-3fa38070dbd7
    go: downloading gopkg.in/src-d/go-git.v4 v4.13.1
    go: downloading google.golang.org/protobuf v1.24.0
    go: downloading github.com/spf13/pflag v1.0.3
    go: downloading github.com/uber/jaeger-lib v2.2.0+incompatible
    go: downloading go.uber.org/atomic v1.6.0
    go: downloading google.golang.org/genproto v0.0.0-20200608115520-7c474a2e3482
    go: downloading github.com/mattn/go-runewidth v0.0.8
    go: downloading gopkg.in/yaml.v2 v2.2.8
    go: downloading github.com/sabhiram/go-gitignore v0.0.0-20180611051255-d3107576ba94
    go: downloading github.com/gofrs/flock v0.7.1
    go: downloading github.com/gofrs/uuid v3.3.0+incompatible
    go: downloading github.com/opentracing/basictracer-go v1.0.0
    go: downloading github.com/gogo/protobuf v1.3.1
    go: downloading golang.org/x/sys v0.0.0-20200602225109-6fdc65e7d980
    go: downloading github.com/sergi/go-diff v1.1.0
    go: downloading gopkg.in/src-d/go-billy.v4 v4.3.2
    go: downloading github.com/jbenet/go-context v0.0.0-20150711004518-d14ea06fba99
    go: downloading github.com/emirpasic/gods v1.12.0
    go: downloading github.com/src-d/gcfg v1.4.0
    go: downloading github.com/kevinburke/ssh_config v0.0.0-20190725054713-01f96b0aa0cd
    go: downloading github.com/mitchellh/go-homedir v1.1.0
    go: downloading github.com/xanzy/ssh-agent v0.2.1
    go: downloading golang.org/x/text v0.3.2
    go: downloading gopkg.in/warnings.v0 v0.1.2


Do you want to perform this update? yes
Updating (dev)

View Live: https://app.pulumi.com/leezen/aws-go/dev/updates/1

     Type                 Name        Status
 +   pulumi:pulumi:Stack  aws-go-dev  created
 +   └─ aws:s3:Bucket     my-bucket   created

Outputs:
    bucketName: "my-bucket-76b08d5"

Resources:
    + 2 created

Duration: 6s

```

Any chance you could please provide more details about your environment? What version of Go and operating system are you on?
