### ISSUE TITLE
Python SDK - Code related HTML elements have unecessary visible overflow

### ISSUE THREAD

**Issue by aureq** [pulumi/docs#6148]
### Problem description

When reading the Python documentation, I noticed some of the code references have "elevators" around them. However, non of them are actionable since the content fits within the element.

I think the reader's experience could be improved by adding `overflow: hidden` on those elements. (See below)

URL: https://www.pulumi.com/docs/reference/pkg/python/pulumi/#pulumi.ProviderResource

Current state
![2021-06-17 12_58_47-Package pulumi _ Python SDK _ Pulumi — Mozilla Firefox](https://user-images.githubusercontent.com/1161681/122325170-6c486200-cf6d-11eb-9706-ea5c674f84c0.png)

New state with `overflow: hidden`
![2021-06-17 13_02_51-Package pulumi _ Python SDK _ Pulumi — Mozilla Firefox](https://user-images.githubusercontent.com/1161681/122325206-7f5b3200-cf6d-11eb-9a42-73eb8d6002bf.png)

### Suggestions for a fix
I used FF web tool and updated the CSS like this

```css
div.section[id]:not([id=""]) dl.class dt, div.section[id]:not([id=""]) dl.function dt, div.section[id]:not([id=""]) dl.exception dt {
  overflow: hidden;
}
```
Related to [4615](https://github.com/pulumi/docs/issues/4615)
