### ISSUE TITLE
some notes have extra line break at the end of the final paragraph

### ISSUE THREAD

**Issue by anita-trimbur** [pulumi/docs#9531]
## overview
some of documentation notes have an extra line break after the final paragraph. this seems occur mostly on multi-paragraph notes and notes that use code blocks.

## screenshot
<img width="1001" alt="Screen Shot 2023-07-21 at 4 06 53 PM" src="https://github.com/pulumi/docs/assets/97129308/5b332320-da05-4d69-87da-15a1380a33f8">

**Comment by thoward** [comment]
This CSS nit is happening because the rule:

```css
.docs-list-main .docs-main-content section.docs-content p {
    /** snip **/
    padding: 0 0 12px;
}
```

is overriding this rule (which is also targeting the wrong property `margin-bottom` vs `padding-bottom`):
```css
.note :last-child {
    margin-bottom: 0;
}
```

When manually updating that to have the same level of specificity, and target the right property, it works as expected.
```css
.docs-main-content section.docs-content .note :last-child {
    margin-bottom: 0;
    padding-bottom: 0;
}
```

I will look into the SCSS for this and see if it's an easy fix. if so will fix next week (or @sean1588 or @shughes26 could fix before me if they want!)
